function [poly] = make_rect(center, length)
%MAKE_SQUARE Summary of this function goes here
%   Detailed explanation goes here
poly = polyshape(...
    [center(1) + length(1) / 2, center(1) + length(1) / 2, ...
    center(1) - length(1) / 2, center(1) - length(1) / 2], ...
    [center(2) + length(2) / 2, center(2) - length(2) / 2, ...
    center(2) - length(2) / 2, center(2) + length(2) / 2]);

end

